name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file melodic/Dockerfile --tag ros-vnc:melodic
        # docker build . --file noetic/Dockerfile --tag ros-vnc:noetic
