name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg DISTRO=bionic --build-arg ROS_VER=melodic --tag ros-vnc:melodic
      run: docker build . --file Dockerfile --build-arg DISTRO=focal --build-arg ROS_VER=noetic --tag ros-vnc:noetic
